-- ========================================
-- V1__initial_schema.sql
-- ========================================

-- Users
CREATE TABLE app_user
(
    uuid  UUID         NOT NULL,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    roles SMALLINT,
    CONSTRAINT pk_app_user PRIMARY KEY (uuid)
);

-- Reference table
CREATE TABLE reference
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- Reference type: 1 = project, 2 = goal, 3 = step, 4 = workout, 5 = recipe, 6 = menu_item
    ref_type    SMALLINT                                NOT NULL,
    ref_id      BIGINT                                  NOT NULL,

    CONSTRAINT pk_reference PRIMARY KEY (id)
);

-- Logs
CREATE TABLE log
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    archived BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_log PRIMARY KEY (id)
);

-- Entries
CREATE TABLE entry
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_id      BIGINT                                  NOT NULL,
    reference_id BIGINT,
    title       VARCHAR(100)                            NOT NULL,
    description TEXT,
    scoring     INTEGER                                 NOT NULL,
    entry_type  SMALLINT                                NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_entry PRIMARY KEY (id),
    CONSTRAINT fk_entry_log FOREIGN KEY (log_id)
        REFERENCES log (id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_reference FOREIGN KEY (reference_id)
        REFERENCES reference(id) ON DELETE SET NULL
);

-- Projects
CREATE TABLE project
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_user_uuid UUID                                    NOT NULL,
    log_id        BIGINT                                  NOT NULL,
    title         VARCHAR(100)                            NOT NULL,
    description   TEXT,
    archived      BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_project PRIMARY KEY (id),
    CONSTRAINT fk_project_user FOREIGN KEY (app_user_uuid)
        REFERENCES app_user (uuid),
    CONSTRAINT fk_project_log FOREIGN KEY (log_id)
        REFERENCES log (id) ON DELETE CASCADE
);

-- Goals
CREATE TABLE goal
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id  BIGINT                                  NOT NULL,
    title       VARCHAR(100)                            NOT NULL,
    description TEXT,
    priority    SMALLINT                                NOT NULL,
    estimated INTERVAL,
    CONSTRAINT pk_goal PRIMARY KEY (id),
    CONSTRAINT fk_goal_project FOREIGN KEY (project_id)
        REFERENCES project (id) ON DELETE CASCADE
);

-- Steps
CREATE TABLE step
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goal_id      BIGINT                                  NOT NULL,
    sequence     INTEGER                                 NOT NULL,
    objective    VARCHAR(100)                            NOT NULL,
    description  TEXT,
    requirements TEXT,
    status       SMALLINT                                NOT NULL,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_step PRIMARY KEY (id),
    CONSTRAINT fk_step_goal FOREIGN KEY (goal_id)
        REFERENCES goal (id) ON DELETE CASCADE
);

-- Events
CREATE TABLE event
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_user_uuid UUID                                    NOT NULL,
    reference_id BIGINT,
    title         VARCHAR(100)                            NOT NULL,
    description   TEXT,
    start         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    stop          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_user FOREIGN KEY (app_user_uuid)
        REFERENCES app_user (uuid),
    CONSTRAINT fk_event_reference FOREIGN KEY (reference_id)
        REFERENCES reference(id) ON DELETE SET NULL
);

-- ========================================
-- Indexes
-- ========================================

CREATE INDEX idx_project_user ON project (app_user_uuid);
CREATE INDEX idx_project_log ON project (log_id);

CREATE INDEX idx_goal_project ON goal (project_id);
CREATE INDEX idx_step_goal ON step(goal_id);

CREATE INDEX idx_event_user ON event(app_user_uuid);

CREATE INDEX idx_entry_log ON entry(log_id);
CREATE INDEX idx_entry_reference ON entry(reference_id);
CREATE INDEX idx_event_reference ON event(reference_id);
